#!/usr/bin/env python3
"""Embed a Lua source file as a C string literal header (build-time only).
Usage: embed_lua.py <in.lua> <out.h> <symbol>
No minification: the header stays reviewable. No game content involved."""
import sys

src, dst, sym = sys.argv[1], sys.argv[2], sys.argv[3]
with open(src, encoding="utf-8") as f:
    body = f.read()


def cstr(s):
    out = []
    for ch in s:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append('\\n"\n"')
        elif 32 <= o < 127:
            out.append(ch)
        else:
            out.append("\\%03o" % o)
    return "".join(out)


with open(dst, "w", encoding="utf-8") as f:
    f.write("// Generated by tools/embed_lua.py — do not edit.\n")
    f.write("static const char* %s =\n\"%s\";\n" % (sym, cstr(body)))
print(f"embedded {src} -> {dst} ({len(body)} bytes)")
